#!/usr/bin/env bash
# Options: <output-dir>

set -e

OUT_PREFIX=$1

echo ""
echo "Building Mercurial..."
./parts/mercurial
export PATH=$HOME/mercurial:$PATH

echo ""
echo "Building pyenv..."
git clone git://github.com/yyuu/pyenv.git .pyenv
export PYENV_ROOT=$(pwd)/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"
export C_INCLUDE_PATH=$PYENV_ROOT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$PYENV_ROOT/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$PYENV_ROOT/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$PYENV_ROOT/lib:$LD_LIBRARY_PATH

echo ""
echo "Building SQLite..."
./parts/sqlite $PYENV_ROOT

echo ""
echo "Forgetting about the default python..."
unset PYTHONPATH
unset PYTHONHOME

echo ""
echo "Building Python..."
pyenv install $1
pyenv rehash
pyenv shell $1

echo ""
echo "Building HDF5..."
./parts/hdf5

echo ""
which python
python --version

which pip
pip --version

echo ""
echo "Building other python packages..."
./parts/build-requirements
