#!/usr/bin/env bash
# Options: <output-dir>

OUT_PREFIX=$1

echo ""
echo "Building SQLite..."
./parts/sqlite $PYENV_ROOT

echo ""
echo "Building Python..."
pyenv install $1

echo ""
echo "Installing the AWS cli..."
pip install git+https://github.com/boto/bcdoc.git@develop
pip install git+https://github.com/boto/jmespath.git@develop
pip install git+https://github.com/boto/botocore.git@develop
pip install git+https://github.com/aws/aws-cli.git@develop
