#!/usr/bin/env bash

set -e
HDF5FILE=hdf5-1.8.11-snap16
curl -O ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/hdf5/snapshots/v18/${HDF5FILE}.tar.gz
tar xf ${HDF5FILE}.tar.gz
rm ${HDF5FILE}.tar.gz
cd ${HDF5FILE}
./configure --prefix=$PYENV_ROOT
make
make install
cd -
rm -r ${HDF5FILE}
